name: Build and Push
on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

# env:
#   ## overrides the docker image name (name is repo name with docker- prefix stripped)
#   DOCKER_IMAGE: foobar

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
    steps:
      -
        uses: actions/github-script@v7
        id: set
        with:
          script: |
            const image = '${{ github.event.repository.full_name }}'.toLowerCase().replace(/\/docker-/, '/')
            core.setOutput('image', '${{ env.DOCKER_IMAGE }}' ? '${{ env.DOCKER_IMAGE }}' : image)

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [pre]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      -
        uses: dysnix/find-latest-tag@v1
        id: latest
        with:
          regex: '^v\d'
          compared-to-tag: ${{ github.ref }}
          repository: ${{ github.repository }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ needs.pre.outputs.image }}
          flavor: |
            latest=${{ steps.latest.outputs.newer == 'true' || steps.latest.outputs.equal == 'true' }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          # amd64 is native platform at the moment and should not be specified here to keep amd64 builds fast
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ steps.latest.outputs.newer == 'true' || steps.latest.outputs.equal == 'true' }}
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
